use_frameworks!

platform :ios, '8.0'

target 'UCARRobot_Example' do
  pod 'UCARRobot', :subspecs => ['Core','WithLogger','UCARDokit','WithLoad'], :path => '../'
  
  pod 'AFNetworking','2.6.3'
  pod 'SDWebImage','3.8.2'
  pod 'CocoaLumberjack'
  
end
